const data = [
  "Account Management",
  "Account Management Cryptography",
  "Accounting",
  "Accounting Agile Software Development",
  "Accounting Software",
  "Accounts Payable and Receivable",
  "Adaptability",
  "Advertising",
  "Agile Software Development",
  "Algebra",
  "Algebra Computer Programming",
  "Algorithms",
  "Amazon Web Services",
  "Android Development",
  "Apache",
  "Application Development",
  "Application Development Applied Machine Learning",
  "Application Development Computational Logic",
  "Applied Machine Learning",
  "Applied Mathematics",
  "Artificial Neural Networks",
  "Artificial Neural Networks Creativity",
  "Audit",
  "Audit Leadership and Management",
  "B2B Sales",
  "Back-End Web Development",
  "Banking",
  "Basic Descriptive Statistics",
  "Basic Descriptive Statistics Business Analysis",
  "Basic Descriptive Statistics Probability & Statistics",
  "Bayesian Statistics",
  "Bayesian Statistics Google Cloud Platform",
  "Behavioral Economics",
  "Benefits",
  "Benefits Estimation",
  "Benefits Security Engineering",
  "Big Data",
  "Big Data Business Analysis",
  "Big Data Cloud Computing",
  "Billing & Invoicing",
  "Bioinformatics",
  "Bioinformatics General Statistics",
  "Biostatistics",
  "BlockChain",
  "BlockChain FinTech",
  "Brand Management",
  "Budget Management",
  "Budget Management Brand Management",
  "Business Analysis",
  "Business Communication",
  "Business Design",
  "Business Development",
  "Business Intelligence",
  "Business Process Management",
  "Business Process Management Process Analysis",
  "Business Psychology",
  "Business Research",
  "Business Transformation",
  "C Programming Language Family",
  "C++ Programming",
  "Calculus",
  "Calculus C Programming Language Family",
  "Calculus Data Analysis",
  "Calculus Data Management",
  "Calculus Design and Product",
  "Cash Management",
  "Change Management",
  "Clinical Data Management",
  "Cloud API",
  "Cloud API Databases",
  "Cloud Applications",
  "Cloud Clients",
  "Cloud Computing",
  "Cloud Computing Cloud Computing",
  "Cloud Computing Cloud Computing Cloud Computing",
  "Cloud Computing Machine Learning",
  "Cloud Engineering",
  "Cloud Infrastructure",
  "Cloud Infrastructure Cloud Applications",
  "Cloud Load Balancing",
  "Cloud Management",
  "Cloud Platforms",
  "Cloud Platforms Cloud Applications",
  "Cloud Platforms Cloud Computing",
  "Cloud Platforms Cloud Computing Leadership and Management",
  "Cloud Platforms Javascript",
  "Cloud Platforms Security Engineering",
  "Cloud Standards",
  "Cloud Standards Cloud Computing",
  "Cloud Storage",
  "Cloud Storage Algebra",
  "Cloud Storage Data Analysis",
  "Cloud-Based Integration",
  "Collaboration",
  "Collaboration Critical Thinking",
  "Combinatorics",
  "Communication",
  "Communication ArcGIS",
  "Communication Artificial Neural Networks",
  "Communication Cloud Computing",
  "Communication Data Analysis",
  "Communication Human Resources",
  "Communication Javascript",
  "Communication Leadership and Management",
  "Communication Mathematical Theory & Analysis",
  "Compensation",
  "Computational Logic",
  "Computational Thinking",
  "Computational Thinking Business Analysis",
  "Computational Thinking Computer Programming",
  "Computer Architecture",
  "Computer Architecture Bioinformatics",
  "Computer Graphic Techniques",
  "Computer Graphics",
  "Computer Graphics Data Analysis",
  "Computer Networking",
  "Computer Networking Customer Relationship Management",
  "Computer Networking FinTech",
  "Computer Programming",
  "Computer Programming Business Analysis",
  "Computer Programming Cloud Computing",
  "Computer Programming Communication",
  "Computer Programming Computational Thinking",
  "Computer Programming Computer Networking",
  "Computer Programming Data Management",
  "Computer Programming Leadership and Management",
  "Computer Programming Network Security Risk Management Javascript",
  "Computer Programming Tools",
  "Computer Programming User Experience",
  "Computer Science",
  "Computer Science Network Security",
  "Computer Security Incident Management",
  "Computer Security Models",
  "Computer Vision",
  "Conflict Management",
  "Conflict Management Design and Product",
  "Conflict Management Sales",
  "Continuous Delivery",
  "Continuous Integration",
  "Contract Management",
  "Contract Management Creativity",
  "Corporate Accouting",
  "Correlation And Dependence",
  "Correlation And Dependence Leadership and Management",
  "Correlation And Dependence Machine Learning",
  "Cost Accounting",
  "Creativity",
  "Creativity Data Analysis",
  "Critical Thinking",
  "Critical Thinking Leadership and Management",
  "Critical Thinking Machine Learning",
  "Critical Thinking SQL General Statistics",
  "Cross Platform Development",
  "Cryptography",
  "Cryptography Leadership and Management Security Engineering",
  "Culture",
  "Culture Cloud Computing",
  "Culture Communication",
  "Culture Project Management",
  "Culture Taxes",
  "Customer Analysis",
  "Customer Analysis Finance",
  "Customer Relationship Management",
  "Customer Relationship Management Algorithms",
  "Customer Success",
  "Customer Support",
  "Cyberattacks",
  "Data Analysis",
  "Data Analysis Amazon Web Services",
  "Data Analysis Communication Business Psychology",
  "Data Analysis Creativity",
  "Data Analysis Databases",
  "Data Analysis Software",
  "Data Architecture",
  "Data Architecture Cloud Applications",
  "Data Engineering",
  "Data Management",
  "Data Management Business Communication",
  "Data Management Data Analysis",
  "Data Management Google Cloud Platform Cloud Computing",
  "Data Management Machine Learning",
  "Data Mining",
  "Data Mining Cloud Applications",
  "Data Mining Data Analysis",
  "Data Model",
  "Data Science",
  "Data Science Algebra",
  "Data Science Algorithms",
  "Data Science Cloud Computing",
  "Data Science Communication",
  "Data Science Creativity",
  "Data Science Data Analysis",
  "Data Science Data Model",
  "Data Science Databases",
  "Data Science Machine Learning",
  "Data Science Mergers & Acquisitions",
  "Data Science Natural Language Processing",
  "Data Science Process Analysis",
  "Data Science Python Programming",
  "Data Science R Programming",
  "Data Science Software Engineering",
  "Data Structures",
  "Data Structures Artificial Neural Networks",
  "Data Visualization",
  "Data Visualization Data Analysis",
  "Data Visualization Econometrics",
  "Data Visualization Finance",
  "Data Visualization Leadership and Management",
  "Data Visualization Software",
  "Data Visualization Software Bioinformatics",
  "Data Visualization Software Python Programming",
  "Data Visualization Software Spreadsheet Software",
  "Data Warehousing",
  "Data Warehousing Cloud Computing Business Analysis",
  "Data Warehousing Computer Programming",
  "Database Administration",
  "Database Administration Business Intelligence",
  "Database Application",
  "Database Application Communication",
  "Database Design",
  "Database Theory",
  "Database Theory Python Programming",
  "Databases",
  "Databases Amazon Web Services",
  "Databases Product Design",
  "Decision Making",
  "Decision Making Business Analysis",
  "Decision Making Data Analysis",
  "Decision Making Security Engineering",
  "Deep Learning",
  "Design and Product",
  "Design and Product Data Management",
  "DevOps",
  "DevOps Cloud Applications",
  "Devops Tools",
  "Differential Equations",
  "Digital Marketing",
  "Dimensionality Reduction",
  "Distributed Computing Architecture",
  "Django (Web Framework)",
  "Docker (Software)",
  "Docker (Software) Applied Machine Learning",
  "Docker (Software) Cloud Applications",
  "E-Commerce",
  "E-Commerce Security Engineering",
  "Econometrics",
  "Emotional Intelligence",
  "Emotional Intelligence Continuous Delivery",
  "Emotional Intelligence General Statistics",
  "Employee Relations",
  "Entrepreneurial Finance",
  "Entrepreneurship",
  "Entrepreneurship Cryptography",
  "Entrepreneurship Digital Marketing",
  "Entrepreneurship Leadership and Management",
  "Entrepreneurship Linux",
  "Entrepreneurship React (web framework)",
  "Epidemiology Algorithms",
  "Estimation",
  "Estimation Algorithms",
  "Experiment",
  "Experiment Cryptography",
  "Experiment Project Management",
  "Exploratory Data Analysis",
  "Exploratory Data Analysis Computer Programming",
  "Exploratory Data Analysis Data Analysis",
  "Exploratory Data Analysis Finance",
  "Extract",
  "Feature Engineering",
  "Feature Engineering Data Analysis",
  "FinTech",
  "FinTech FinTech",
  "FinTech Finance",
  "Finance",
  "Finance FinTech",
  "Finance Writing",
  "Financial Accounting",
  "Financial Accounting Computer Programming",
  "Financial Analysis",
  "Financial Management",
  "Forecasting",
  "Forecasting Finance",
  "Forecasting Python Programming",
  "Front-End Web Development",
  "Full-Stack Web Development",
  "Full-Stack Web Development Application Development",
  "GIS Software",
  "Game Theory",
  "General Accounting",
  "General Statistics",
  "General Statistics Computer Programming",
  "General Statistics Data Visualization",
  "General Statistics General Statistics Regression Mathematics",
  "Generally Accepted Accounting Principles (GAAP)",
  "Geometry",
  "Geometry General Statistics",
  "Geostatistics",
  "Geovisualization",
  "Google App Engine",
  "Google App Engine Cloud Computing",
  "Google App Engine Computer Programming",
  "Google Cloud Platform",
  "Google Cloud Platform Cloud Computing",
  "Google Cloud Platform Cloud Computing Cloud Applications",
  "Google Cloud Platform Cloud Computing Cloud Computing",
  "Google Cloud Platform Communication",
  "Graph Theory",
  "Graph Theory Data Analysis",
  "Graph Theory Regulations and Compliance",
  "Graphic Design",
  "Graphic Design Cloud Computing Cloud Applications",
  "Graphics Software",
  "HTML and CSS",
  "HTML and CSS Software Engineering",
  "Hardware Design",
  "Human Computer Interaction",
  "Human Factors (Security)",
  "Human Factors (Security) BlockChain",
  "Human Learning",
  "Human Learning Business Analysis",
  "Human Learning Emotional Intelligence",
  "Human Learning Probability & Statistics",
  "Human Resources",
  "Human Resources Operations",
  "IBM Cloud",
  "IBM Cloud Cloud Computing",
  "IBM Cloud Computer Programming",
  "IBM Cloud Creativity",
  "IBM Cloud Data Analysis",
  "IBM Cloud Data Management",
  "Influencing",
  "Information Technology",
  "Information Technology Planning",
  "Innovation",
  "Innovation Digital Marketing",
  "Innovation FinTech",
  "Innovation Procurement",
  "Insurance Sales",
  "Interactive Data Visualization",
  "Interactive Data Visualization General Statistics",
  "Interactive Data Visualization Statistical Programming",
  "Interactive Design",
  "Interactive Design Python Programming",
  "Internet Of Things",
  "Internet Of Things Computer Security Incident Management",
  "Inventory Management",
  "Investment Management",
  "Investment Management Communication",
  "Java Programming",
  "Java Programming Algorithms",
  "Javascript",
  "Javascript Communication",
  "Jira (Software) BlockChain",
  "Journalism Human Resources",
  "Knitr",
  "Kubernetes",
  "Kubernetes Cloud Computing",
  "Kubernetes Data Analysis Digital Marketing",
  "Kubernetes Google Cloud Platform",
  "Kubernetes Machine Learning",
  "Kubernetes Project Management",
  "Leadership Development",
  "Leadership and Management",
  "Leadership and Management Algebra",
  "Leadership and Management Amazon Web Services",
  "Leadership and Management Artificial Neural Networks",
  "Leadership and Management Banking",
  "Leadership and Management Basic Descriptive Statistics",
  "Leadership and Management Benefits",
  "Leadership and Management Cloud Applications",
  "Leadership and Management Cloud Computing",
  "Leadership and Management Communication",
  "Leadership and Management Computer Networking",
  "Leadership and Management Computer Programming",
  "Leadership and Management Cryptography",
  "Leadership and Management Data Analysis",
  "Leadership and Management Design and Product",
  "Leadership and Management Digital Marketing",
  "Leadership and Management Financial Management",
  "Leadership and Management General Statistics",
  "Leadership and Management Internet Of Things",
  "Leadership and Management Leadership and Management",
  "Leadership and Management Machine Learning",
  "Leadership and Management Microsoft Excel",
  "Leadership and Management Network Security",
  "Leadership and Management Python Programming",
  "Leadership and Management R Programming",
  "Leadership and Management Resilience Data Analysis",
  "Leadership and Management Security Engineering",
  "Linear Algebra",
  "Linear Algebra Computer Programming",
  "Linear Algebra Critical Thinking",
  "Linear Algebra Machine Learning",
  "Linux",
  "Linux Bioinformatics",
  "Linux Software Engineering",
  "Load",
  "Load Data Analysis",
  "Load System Security",
  "Machine Learning",
  "Machine Learning Algorithms",
  "Machine Learning Algorithms Data Analysis",
  "Machine Learning Cloud Computing",
  "Machine Learning Computer Networking",
  "Machine Learning Data Analysis",
  "Machine Learning Kubernetes",
  "Machine Learning Leadership and Management",
  "Machine Learning Linux",
  "Machine Learning Software",
  "Machine Learning Software Exploratory Data Analysis User Experience",
  "Management Accounting",
  "Management Accounting Data Analysis",
  "Market Analysis",
  "Market Analysis Organizational Development",
  "Market Analysis Python Programming",
  "Market Research",
  "Market Research Artificial Neural Networks",
  "Marketing",
  "Marketing Computer Security Incident Management",
  "Marketing Design",
  "Marketing Management",
  "Marketing Psychology",
  "Markov Model",
  "Material Handling",
  "Mathematical Theory & Analysis",
  "Mathematical Theory & Analysis General Statistics",
  "Mathematics",
  "Mathematics Clinical Data Management",
  "Mathematics Data Analysis",
  "Matlab",
  "Matlab Data Analysis",
  "Matlab HTML and CSS",
  "Media Strategy & Planning",
  "Mergers & Acquisitions",
  "Mergers & Acquisitions Collaboration",
  "Mergers & Acquisitions Creativity",
  "Mergers & Acquisitions Data Analysis",
  "Mergers & Acquisitions Leadership and Management Machine Learning",
  "Mergers & Acquisitions Machine Learning",
  "Microarchitecture",
  "Microsoft Azure",
  "Microsoft Azure Cloud Computing",
  "Microsoft Excel",
  "Microsoft Excel Amazon Web Services",
  "Microsoft Excel BlockChain",
  "Microsoft Excel FinTech",
  "Microsoft Excel Machine Learning",
  "Microsoft Excel Mathematics",
  "Microsoft Excel Operating Systems",
  "Minitab Big Data",
  "Mobile Development",
  "Mobile Development Tools",
  "Mobile Security",
  "Mobile Security Finance",
  "Mobile Security Leadership and Management",
  "Natural Language Processing",
  "Natural Language Processing Cloud Computing",
  "Natural Language Processing Linux",
  "Negotiation",
  "Network Analysis",
  "Network Architecture",
  "Network Architecture Cloud Computing",
  "Network Architecture Cloud Infrastructure",
  "Network Architecture Google Cloud Platform",
  "Network Architecture Network Architecture",
  "Network Model",
  "Network Model Leadership and Management",
  "Network Security",
  "Network Security Business Analysis",
  "Network Security Computer Networking",
  "Networking Hardware",
  "Networking Hardware Natural Language Processing",
  "NoSQL",
  "NoSQL Data Analysis",
  "NoSQL Design and Product",
  "NoSQL Google Cloud Platform",
  "NoSQL Microsoft Excel",
  "Operating Systems",
  "Operating Systems Data Analysis",
  "Operating Systems Finance",
  "Operating Systems Machine Learning",
  "Operational Analysis",
  "Operations Management",
  "Operations Management Audit",
  "Operations Management Cloud Computing",
  "Operations Management Communication",
  "Operations Management Critical Thinking",
  "Operations Management Research and Design",
  "Operations Research",
  "Organizational Development",
  "Organizational Development DevOps",
  "Other Cloud Platforms and Tools",
  "Other Programming Languages",
  "Other Web Frameworks",
  "Payments",
  "Payments BlockChain",
  "Payments FinTech",
  "People Analysis",
  "People Development",
  "People Development Mergers & Acquisitions",
  "People Management",
  "People Management Artificial Neural Networks",
  "Performance Management",
  "Performance Management Human Learning",
  "Persona Research",
  "Persona Research Python Programming",
  "Planning",
  "Planning Agile Software Development",
  "Planning Amazon Web Services",
  "Planning Business Communication",
  "Planning Cloud Computing",
  "Planning Communication",
  "Planning Data Engineering",
  "Planning Data Science",
  "Planning Leadership and Management",
  "Planning Machine Learning",
  "Planning Planning Problem Solving Market Analysis",
  "Planning Python Programming",
  "Planning Security Engineering",
  "Plot (Graphics)",
  "PostgreSQL",
  "PostgreSQL Computer Programming",
  "PostgreSQL DevOps",
  "Power BI",
  "Power BI Mathematics",
  "Probability & Statistics",
  "Probability & Statistics Deep Learning",
  "Probability & Statistics FinTech",
  "Probability Distribution",
  "Probability Distribution Communication Artificial Neural Networks",
  "Probability Distribution Mathematics",
  "Probability Distribution Operations Management Human Factors (Security)",
  "Problem Solving",
  "Problem Solving Bioinformatics",
  "Problem Solving Communication",
  "Problem Solving Computer Programming",
  "Problem Solving Data Analysis",
  "Problem Solving Entrepreneurship",
  "Problem Solving Machine Learning",
  "Problem Solving Security Strategy",
  "Process Analysis",
  "Process Analysis Algorithms",
  "Process Analysis Computer Graphics",
  "Procurement Finance",
  "Procurement Marketing",
  "Procurement Python Programming",
  "Product Design",
  "Product Development",
  "Product Development Business Intelligence",
  "Product Lifecycle",
  "Product Management",
  "Product Marketing",
  "Product Strategy",
  "Product Strategy Applied Machine Learning",
  "Professional Development",
  "Professional Development Agile Software Development",
  "Professional Development Computer Networking",
  "Professional Development Machine Learning",
  "Programming Principles",
  "Programming Principles Algorithms",
  "Programming Principles Human Learning",
  "Project Management",
  "Project Management Business Analysis",
  "Project Management Data Analysis",
  "Project Management DevOps",
  "Project Management Finance",
  "Prospecting and Qualification",
  "Public Relations",
  "Python Programming",
  "Python Programming Algorithms",
  "Python Programming Business Intelligence",
  "Python Programming Cloud Computing",
  "Python Programming Cloud Computing Cloud Applications",
  "Python Programming Communication",
  "Python Programming Computer Programming",
  "Python Programming Computer Security Incident Management",
  "Python Programming Data Analysis",
  "Python Programming Data Management",
  "Python Programming Data Science",
  "Python Programming Epidemiology",
  "Python Programming Inventory Management",
  "Python Programming Leadership and Management",
  "Python Programming Machine Learning General Statistics",
  "Python Programming Marketing",
  "Python Programming Microsoft Azure",
  "Python Programming Probability & Statistics",
  "Python Programming User Experience",
  "R Programming",
  "R Programming Data Management",
  "React (web framework)",
  "React (web framework) Accounting",
  "React (web framework) Agile Software Development",
  "React (web framework) Cloud Computing",
  "React (web framework) Data Science",
  "React (web framework) DevOps",
  "Recruitment",
  "Recruitment Artificial Neural Networks",
  "Recruitment BlockChain",
  "Recruitment Machine Learning",
  "Regression",
  "Regression Basic Descriptive Statistics",
  "Regression Computer Security Incident Management",
  "Regression Data Analysis",
  "Regression Leadership and Management",
  "Regression Machine Learning",
  "Regulations and Compliance",
  "Regulations and Compliance BlockChain",
  "Regulations and Compliance Cloud Computing",
  "Regulations and Compliance Computational Logic",
  "Regulations and Compliance FinTech",
  "Regulations and Compliance Human Computer Interaction",
  "Regulations and Compliance Supply Chain and Logistics",
  "Reinforcement Learning",
  "Reinforcement Learning User Experience",
  "Research and Design",
  "Research and Design BlockChain",
  "Research and Design Machine Learning",
  "Retail Sales",
  "Retail Store Operations Python Programming",
  "Risk Management",
  "Risk Management BlockChain",
  "Risk Management Cyberattacks",
  "Risk Management Data Management",
  "Risk Management DevOps",
  "Risk Management Digital Marketing",
  "Risk Management Front-End Web Development",
  "Risk Management Machine Learning",
  "Risk Management Mobile Security",
  "Risk Management Network Security",
  "Risk Management Python Programming",
  "Risk Management User Experience",
  "SAS (Software)",
  "SQL",
  "SQL Big Data",
  "SQL Cloud Applications",
  "SQL Computer Programming",
  "SQL Data Analysis",
  "SQL Google Cloud Platform",
  "SQL Human Learning",
  "SQL Leadership and Management",
  "SQL Project Management",
  "SQL Python Programming",
  "SQL Strategy",
  "Sales",
  "Sales Algorithms",
  "Sales Systems",
  "Salesforce",
  "Salesforce Brand Management",
  "Salesforce Customer Relationship Management",
  "Scientific Visualization",
  "Scrum (Software Development)",
  "Search Engine Optimization",
  "Search Engine Optimization Entrepreneurial Finance",
  "Securities Sales",
  "Securities Trading",
  "Securities Trading Banking",
  "Securities Trading BlockChain",
  "Securities Trading FinTech",
  "Security Engineering",
  "Security Engineering BlockChain",
  "Security Engineering Finance",
  "Security Engineering Human Resources",
  "Security Engineering Network Security",
  "Security Software",
  "Security Strategy",
  "Security Strategy Business Development",
  "Security Strategy Entrepreneurship",
  "Semantic Web",
  "Shipping and Receiving",
  "Small Data",
  "Small Data Leadership and Management",
  "Small Data Visual Design",
  "Social Media",
  "Social Media Entrepreneurship",
  "Social Media Machine Learning",
  "Software Architecture",
  "Software Architecture Data Management",
  "Software As A Service",
  "Software As A Service Strategy",
  "Software Engineering",
  "Software Engineering Accounting",
  "Software Engineering Big Data",
  "Software Engineering Customer Success",
  "Software Engineering Data Analysis",
  "Software Engineering Data Management",
  "Software Engineering Planning Recruitment",
  "Software Engineering Tools",
  "Software Engineering Tools Cloud Computing",
  "Software Framework",
  "Software Security",
  "Software Security BlockChain",
  "Software Testing",
  "Software Testing Cloud Computing",
  "Software Testing Collaboration",
  "Software Testing Machine Learning",
  "Software-Defined Networking",
  "Software-Defined Networking Cloud Computing",
  "Software-Defined Networking User Experience",
  "Spatial Analysis",
  "Spatial Data Analysis",
  "Spreadsheet Software",
  "Spreadsheet Software Data Analysis",
  "Spreadsheet Software Leadership and Management",
  "Statistical Analysis",
  "Statistical Analysis Accounting",
  "Statistical Analysis Data Visualization",
  "Statistical Analysis Databases",
  "Statistical Analysis HTML and CSS",
  "Statistical Analysis Probability & Statistics",
  "Statistical Analysis Software Engineering",
  "Statistical Analysis Virtual Reality",
  "Statistical Machine Learning",
  "Statistical Machine Learning BlockChain",
  "Statistical Machine Learning Writing",
  "Statistical Programming",
  "Statistical Programming Application Development",
  "Statistical Programming Applied Machine Learning",
  "Statistical Programming Calculus",
  "Statistical Programming Computer Networking",
  "Statistical Programming General Statistics",
  "Statistical Tests",
  "Statistical Tests Human Learning",
  "Statistical Tests Machine Learning",
  "Statistical Tests Probability & Statistics",
  "Statistical Visualization",
  "Statistical Visualization Communication Leadership and Management",
  "Statistical Visualization Computer Programming",
  "Statistical Visualization Human Resources",
  "Store Management",
  "Storytelling",
  "Storytelling Computer Programming",
  "Storytelling Natural Language Processing Cryptography",
  "Strategy",
  "Strategy BlockChain",
  "Strategy Cloud Computing",
  "Strategy Computer Security Incident Management",
  "Strategy Customer Relationship Management",
  "Strategy Graphic Design",
  "Strategy HTML and CSS",
  "Strategy Leadership and Management",
  "Strategy Marketing",
  "Strategy and Operations",
  "Strategy and Operations Cloud Computing",
  "Strategy and Operations Investment Management",
  "Supplier Relationship Management",
  "Supplier Relationship Management Linux",
  "Supply Chain Systems",
  "Supply Chain and Logistics",
  "Supply Chain and Logistics Algebra",
  "Supply Chain and Logistics Cloud Computing",
  "Supply Chain and Logistics Python Programming",
  "Supply Chain and Logistics Strategy",
  "Survey Creation",
  "Swift Programming",
  "System Programming",
  "System Security",
  "System Security Accounting",
  "System Security Applied Machine Learning",
  "System Security Big Data",
  "System Security BlockChain",
  "System Security Digital Marketing",
  "System Security Linux Leadership and Management",
  "System Security Software Engineering",
  "System Software",
  "System Software Banking",
  "Systems Design",
  "Systems Design BlockChain",
  "Systems Design Brand Management",
  "Systems Design FinTech",
  "Tableau Software",
  "Tableau Software Apache",
  "Tableau Software Computer Security Incident Management",
  "Tableau Software Data Analysis",
  "Tableau Software Finance",
  "Tableau Software General Statistics",
  "Tableau Software Mathematics",
  "Tableau Software Project Management",
  "Tableau Software SQL",
  "Talent Management",
  "Taxes",
  "Taxes Linux",
  "Taxes Mobile Development",
  "Technical Product Management",
  "Tensorflow",
  "Tensorflow Critical Thinking Network Security",
  "Tensorflow Data Analysis",
  "Tensorflow Data Management",
  "Tensorflow Project Management",
  "Tensorflow Supply Chain Systems",
  "Theoretical Computer Science",
  "Theoretical Computer Science Entrepreneurship",
  "Theoretical Computer Science Probability & Statistics",
  "Training",
  "Training Spreadsheet Software",
  "Transform",
  "Transportation Operations Management",
  "Underwriting",
  "Underwriting Accounting",
  "User Experience",
  "User Experience Algebra",
  "User Experience Critical Thinking Collaboration",
  "User Experience Cryptography",
  "User Experience Design",
  "User Experience Design Mathematics",
  "User Experience Health Accounting",
  "User Research",
  "User Research Leadership and Management",
  "User Research Python Programming",
  "Visual Design",
  "Visualization (Computer Graphics)",
  "Visualization (Computer Graphics) Communication",
  "Visualization (Computer Graphics) DevOps",
  "Visualization (Computer Graphics) Leadership and Management",
  "Warehouse Management",
  "Warehouse Management Bioinformatics",
  "Warehouse Management Business Analysis",
  "Web Design",
  "Web Design Computer Programming",
  "Web Design Creativity",
  "Web Design Leadership and Management",
  "Web Design Mobile Development",
  "Web Development",
  "Web Development Cloud Applications",
  "Web Development Cloud Computing",
  "Web Development E-Commerce",
  "Web Development Project Management",
  "Web Development Python Programming",
  "Web Development Tools",
  "Web Development Tools Accounting",
  "Web Development Tools Critical Thinking Cloud Computing",
  "Web Development Tools DevOps",
  "Web Development Tools E-Commerce",
  "Web Development Tools Leadership and Management",
  "Web Development Tools Mathematics",
  "Writing",
  "Writing Audit",
  "Writing Business Analysis",
  "Writing Cloud Computing",
  "Writing Creativity",
  "Writing Data Analysis",
  "Writing Digital Marketing",
  "Writing Emotional Intelligence Design and Product",
  "Writing Finance",
  "Writing Human Learning",
  "Writing Leadership and Management",
  "Writing Machine Learning",
  "Writing Mergers & Acquisitions Writing Marketing",
  "Writing Python Programming",
  "Writing Security Engineering",
  "iOS Development",
  "iOS Development Operating Systems",
];

export default data;
